# quicksort project
bin/quicksort: bin/quicksort.o
	g++ -Wall -std=c++11 bin/quicksort.o -o bin/quicksort

bin/quicksort.o: src/quicksort.cpp
	g++ -Wall -std=c++11 -c src/quicksort.cpp -o bin/quicksort.o

# pi project
bin/pi: bin/pi.o
	g++ -Wall -std=c++11 bin/pi.o -o bin/pi

bin/pi.o: src/pi.cpp
	g++ -Wall -std=c++11 -c src/pi.cpp -o bin/pi.o