# quicksort project
bin/quicksort: bin/quicksort.o
	g++ -Wall -std=c++11 bin/quicksort.o -o bin/quicksort

bin/quicksort.o: src/quicksort.cpp
	g++ -Wall -std=c++11 -c src/quicksort.cpp -o bin/quicksort.o


